{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jupyterhub-metrics.fullname" . }}-grafana
  namespace: {{ include "jupyterhub-metrics.namespace" . }}
  labels:
    {{- include "jupyterhub-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if $.Values.ingress.tls.certManagerIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certManagerIssuer }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jupyterhub-metrics.fullname" . }}-grafana
                port:
                  number: {{ .Values.grafana.port }}
{{- end }}
