{{- if .Values.advanced.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "jupyterhub-metrics.namespace" . }}
  labels:
    {{- include "jupyterhub-metrics.labels" . | nindent 4 }}
    # Pod Security Standards (for Kubernetes 1.25+)
    # Enforce the configured security standard level
    pod-security.kubernetes.io/enforce: {{ .Values.security.podSecurityStandard }}
    pod-security.kubernetes.io/audit: {{ .Values.security.podSecurityStandard }}
    pod-security.kubernetes.io/warn: {{ .Values.security.podSecurityStandard }}
{{- end }}
