apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_NAME}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
      connMaxLifetime: 900
    editable: true
    isDefault: true
